[package]
name = "menu"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.22"

[dev-dependencies]
anyhow = "1.0.98"

[features]
default = []
generate = []